In [1]:
import pandas as pd 
import numpy as np
import re 
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [2]:
nltk.download('punkit')
nltk.download('stopworld')

[nltk_data] Error loading punkit: Package 'punkit' not found in index
[nltk_data] Error loading stopworld: Package 'stopworld' not found in
[nltk_data]     index

False

In [3]:
df = pd.read_csv("Dataset.csv",
encoding= 'ISO-8859-1')
df.head()

C:\Users\ls615\AppData\Local\Temp\ipykernel_21396\853453304.py:1: DtypeWarning: Columns (0: Rate) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Dataset.csv",

,Product_name,Price,Rate,Review,Summary
0,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Simply awesome,it's really worth every single penny. it works...
1,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...
2,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Worth every penny,GREAT packaging by seller. As this was the mos...
3,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",5,Fabulous!,Delivery was delayed by two days except this e...
4,"Crompton 75 L Desert Air Cooler??(White, Tea...","??10,499",4,Nice product,A Good cooler by Crompton. The height of the c...

In [4]:
print(df.columns)

Index(['Product_name', 'Price', 'Rate', 'Review', 'Summary'], dtype='str')

In [5]:
def get_sentiment(rating):
    if rating >= 4:
        return "positive"
    elif rating == 3:
        return "neutral"
    else:
        return "negative"

df['sentiment'] = df['Rate'].apply(get_sentiment)

df.head()

TypeError: '>=' not supported between instances of 'str' and 'int'

In [ ]:
df['sentiment'].value_counts()

sentiment
positive    310204
negative     49456
neutral       3601
Name: count, dtype: int64

In [ ]:
print(df.shape)
print(df.columns)
df.info()
df['sentiment'].value_counts()

(363261, 6)
Index(['Product_name', 'Price', 'Rate', 'Review', 'Summary', 'sentiment'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 363261 entries, 0 to 363260
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_name  363261 non-null  int64
 1   Price         363261 non-null  int64
 2   Rate          363261 non-null  int64
 3   Review        363261 non-null  int64
 4   Summary       363261 non-null  int64
 5   sentiment     363261 non-null  str
dtypes: int64(5), str(1)
memory usage: 16.6 MB

sentiment
positive    310204
negative     49456
neutral       3601
Name: count, dtype: int64

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 363261 entries, 0 to 363260
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_name  363246 non-null  str
 1   Price         363245 non-null  str
 2   Rate          363245 non-null  object
 3   Review        363239 non-null  str
 4   Summary       361239 non-null  str
dtypes: object(1), str(4)
memory usage: 13.9+ MB

Product_name      15
Price             16
Rate              16
Review            22
Summary         2022
dtype: int64

In [ ]:
df = df.fillna(df.mean(numeric_only=True))

In [ ]:
encoder = LabelEncoder()

In [ ]:
le = LabelEncoder()

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col].astype(str))

df.head()

C:\Users\ls615\AppData\Local\Temp\ipykernel_21768\1161814745.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object'):

   Product_name  Price  Rate  Review  Summary
0           189    227     8    2544   155844
1           189    227     6    3326    50127
2           189    227     8    3304    30990
3           189    227     8     862    22097
4           189    227     6    1953     1460

In [ ]:
data = df[["Review","sentiment"]]
data.head()

   Review sentiment
0    2544  positive
1    3326  positive
2    3304  positive
3     862  positive
4    1953  positive

In [ ]:
from sklearn.model_selection import train_test_split

X = data["Review"]
y = data["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
X_train = X_train.astype(str)
X_test = X_test.astype(str)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

Accuracy: 0.9870342587367349

In [ ]:
review = ["This product is very good"]

review_vector = vectorizer.transform(review)  

prediction = model.predict(review_vector)

print("Predicted Sentiment:", prediction[0])

Predicted Sentiment: positive

In [ ]:
X_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 72002 stored elements and shape (72653, 3210)>

In [ ]:
y_test

291794    positive
237546    positive
71917     positive
135863    positive
178743    positive
            ...
19741     positive
241189    negative
169751    positive
19115     positive
262635    positive
Name: sentiment, Length: 72653, dtype: str

In [ ]:
review = ["This product is very good and amazing"]

review_vector = vectorizer.transform(review)

prediction = model.predict(review_vector)

print("Predicted Sentiment:", prediction[0])

Predicted Sentiment: positive